global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']

  - job_name: 'fb-collector'
    static_configs:
      - targets: ['fb-collector:3002']

  - job_name: 'ttk-collector'
    static_configs:
      - targets: ['ttk-collector:3003']

  - job_name: 'reporter'
    static_configs:
      - targets: ['reporter:3000']
